import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface AttendancePDFData {
  clubName: string
  eventName: string
  venueName: string
  date: string
  records: {
    name: string
    rollNumber: string
    time: string
    distanceM: number
    verified: boolean
  }[]
}

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

export function generateAttendancePDF(data: AttendancePDFData): void {
  const doc = new jsPDF()
  const generatedAt = new Date().toLocaleString()
  const safeClub = slugify(data.clubName || 'club')
  const safeDate = slugify(data.date || new Date().toISOString().slice(0, 10))

  doc.setFontSize(18)
  doc.text(data.clubName, 14, 18)
  doc.setFontSize(14)
  doc.text(data.eventName, 14, 27)
  doc.setFontSize(11)
  doc.text(`Venue: ${data.venueName}`, 14, 35)
  doc.text(`Date: ${data.date}`, 14, 42)
  doc.text(`Total records: ${data.records.length}`, 14, 49)

  autoTable(doc, {
    startY: 58,
    head: [['#', 'Name', 'Roll No', 'Time', 'Distance', 'Status']],
    body: data.records.map((record, index) => [
      index + 1,
      record.name,
      record.rollNumber,
      record.time,
      `${record.distanceM} m`,
      record.verified ? 'Verified' : 'Unverified',
    ]),
    styles: {
      fontSize: 10,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [94, 114, 135],
    },
  })

  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(9)
  doc.text(
    `Generated by RDEC Student Portal - ${generatedAt}`,
    14,
    footerY
  )

  doc.save(`${safeClub}-attendance-${safeDate}.pdf`)
}
